name: Deploy React/Vue to IIS via SSH (with password)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy build files to IIS server using password
        run: |
          # Use sshpass to pass the password for SCP and copy to D:/WebSites/voting/
          sshpass -p "${{ secrets.IIS_SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no -r build/* ${{ secrets.IIS_SERVER_USER }}@${{ secrets.IIS_SERVER_HOST }}:"D:/WebSites/voting/"

      - name: Restart IIS site using password
        run: |
          # Use sshpass to pass the password for SSH connection and restart the app pool 'voting'
          sshpass -p "${{ secrets.IIS_SERVER_PASSWORD }}" ssh ${{ secrets.IIS_SERVER_USER }}@${{ secrets.IIS_SERVER_HOST }} powershell -Command "Import-Module WebAdministration; Restart-WebAppPool -Name 'voting'"
